version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_API_KEY:
     secure: lrHMbHQXtZkpSEBS1QuPid9U0BY9pm29ywy9mnB1bYTBr43/X72oPGt59Fxmxz5V
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet